spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope: profile, email
          github:
            scope: user:email, read:user
          kakao:
            redirect-uri: http://ec2-3-34-138-44.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sixman-rds.c2bhjqsi4ogs.ap-northeast-2.rds.amazonaws.com/sixmandb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
url:
  frontend: http://sixman-front-s3.s3-website.ap-northeast-2.amazonaws.com

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:classpath:/application-secret.yml
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
            kakao:
                redirect-uri: http://localhost:8080/login/oauth2/code/kakao
url:
  frontend: http://localhost:3000
