name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew and build with Gradle
        run: |
          cd backend
          chmod +x gradlew
          ./gradlew build
      - name: Docker build
        run: |
          cd backend
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t backend . 
          docker tag backend ${{ secrets.DOCKER_HUB_USERNAME }}/backend:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKER_HUB_PASSWORD }}/backend:${GITHUB_SHA::7}
